# Generated by Django 4.0.5 on 2022-07-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_alter_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='gate',
            field=models.CharField(default='gate1', max_length=8),
        ),
    ]
